# Generated by Django 3.1.7 on 2021-03-28 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('bmp', models.FloatField()),
                ('file', models.FileField(upload_to='video')),
            ],
        ),
        migrations.CreateModel(
            name='OutModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField(blank=True, null=True)),
                ('upload_video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='sub_app.videomodel')),
            ],
        ),
    ]
